default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: username
  password: 123
  pool: 5

development:
  <<: *default
  database: desafio-back-end_development
  
test:
  <<: *default
  database: desafio-back-end_test

production:
  <<: *default
  database: desafio-back-end_production
  username: desafio-back-end
  password: <%= ENV['DESAFIO-BACK-END_DATABASE_PASSWORD'] %>
